// Generated from texas_tdus_by_city.md. Do not edit by hand.
export const TEXAS_TDU_BY_CITY: Record<string, readonly string[]> = {
  'abilene': ['AEP Texas'],
  'abram -perezville': ['AEP Texas'],
  'acme': ['AEP Texas'],
  'adams garden': ['AEP Texas'],
  'addison': ['Oncor'],
  'afton': ['AEP Texas'],
  'agua dulce': ['AEP Texas'],
  'alamo': ['AEP Texas'],
  'albany': ['AEP Texas'],
  'alice': ['CenterPoint', 'AEP Texas'],
  'allen': ['Oncor'],
  'alleyton': ['AEP Texas'],
  'alpine': ['AEP Texas'],
  'alton': ['AEP Texas'],
  'alvarado': ['Oncor'],
  'alvin': ['TNMP'],
  'ames': ['CenterPoint'],
  'anahuac': ['CenterPoint'],
  'andrews': ['Oncor'],
  'angleton': ['TNMP'],
  'anna': ['Oncor'],
  'anson': ['AEP Texas'],
  'aqua dulce': ['CenterPoint'],
  'aransas pass': ['CenterPoint', 'AEP Texas'],
  'archer city': ['Oncor'],
  'argyle': ['Oncor'],
  'arlington': ['Oncor'],
  'arp': ['CenterPoint'],
  'asherton': ['AEP Texas'],
  'aspermont': ['AEP Texas'],
  'atlanta': ['CenterPoint'],
  'aubrey': ['TNMP'],
  'austin': ['CenterPoint'],
  'austwell': ['AEP Texas'],
  'avinger': ['CenterPoint'],
  'avoca': ['AEP Texas'],
  'azle': ['Oncor'],
  'bagwell': ['TNMP'],
  'bailey': ['TNMP'],
  'baileys prairie': ['TNMP'],
  'baird': ['AEP Texas'],
  'bakersfield': ['AEP Texas'],
  'ballinger': ['AEP Texas'],
  'balmorhea': ['AEP Texas'],
  'banquete': ['CenterPoint', 'AEP Texas'],
  'barksdale': ['AEP Texas'],
  'barnhart': ['AEP Texas'],
  'barstow': ['TNMP'],
  'bastrop': ['CenterPoint'],
  'bay city': ['AEP Texas'],
  'bayside': ['AEP Texas'],
  'bayview': ['AEP Texas'],
  'beaumont': ['CenterPoint'],
  'beauxart gardens': ['CenterPoint'],
  'beckville': ['CenterPoint'],
  'bedford': ['Oncor'],
  'beeville': ['CenterPoint', 'AEP Texas'],
  'belcherville': ['TNMP'],
  'bellmead': ['Oncor'],
  'bells': ['TNMP'],
  'belmont': ['AEP Texas'],
  'belton': ['Oncor'],
  'benavides': ['AEP Texas'],
  'benbrook': ['Oncor'],
  'benjamin': ['AEP Texas'],
  'berclair': ['AEP Texas'],
  'best': ['AEP Texas'],
  'beverly hills': ['Oncor'],
  'bevil oaks': ['CenterPoint'],
  'big lake': ['AEP Texas'],
  'big sandy': ['CenterPoint'],
  'big spring': ['Oncor'],
  'big wells': ['AEP Texas'],
  'bishop': ['CenterPoint', 'AEP Texas'],
  'bivins': ['CenterPoint'],
  'blackwell': ['AEP Texas'],
  'blessing': ['CenterPoint', 'AEP Texas'],
  'blewett': ['AEP Texas'],
  'bloomburg': ['CenterPoint'],
  'bloomington': ['CenterPoint', 'AEP Texas'],
  'blossom': ['TNMP'],
  'blue ridge': ['TNMP'],
  'bluetown': ['AEP Texas'],
  'bluffdale': ['TNMP'],
  'blum': ['TNMP'],
  'bogata': ['TNMP'],
  'brackettville': ['AEP Texas'],
  'bradshaw': ['AEP Texas'],
  'breckenridge': ['Oncor'],
  'bridge city': ['CenterPoint'],
  'bridgeport': ['Oncor'],
  'bronte': ['AEP Texas'],
  'brownsville': ['AEP Texas'],
  'brownwood': ['Oncor'],
  'bruni': ['CenterPoint', 'AEP Texas'],
  'bryson': ['TNMP'],
  'buda': ['CenterPoint'],
  'buffalo': ['Oncor'],
  'buffalo gap': ['AEP Texas'],
  'bullard': ['CenterPoint'],
  'buna': ['CenterPoint'],
  'burkburnett': ['Oncor'],
  'burkett': ['AEP Texas'],
  'burleson': ['Oncor'],
  'byers': ['TNMP'],
  'caddo mills': ['Oncor'],
  'cameron': ['Oncor'],
  'camp wood': ['AEP Texas'],
  'campbellton': ['CenterPoint'],
  'canton': ['Oncor'],
  'caps': ['AEP Texas'],
  'carlsbad': ['AEP Texas'],
  'carlton': ['TNMP'],
  'carrizo springs': ['AEP Texas'],
  'carrollton': ['Oncor'],
  'carthage': ['CenterPoint'],
  'cason': ['CenterPoint'],
  'catarina': ['AEP Texas'],
  'cedar creek': ['CenterPoint'],
  'cedar hill': ['Oncor'],
  'celeste': ['TNMP'],
  'celina': ['Oncor'],
  'centerville': ['Oncor'],
  'chapman ranch': ['AEP Texas'],
  'charlotte': ['AEP Texas'],
  'cheek': ['CenterPoint'],
  'childress': ['AEP Texas'],
  'chillicothe': ['AEP Texas'],
  'china': ['CenterPoint'],
  'christine': ['AEP Texas'],
  'christoval': ['AEP Texas'],
  'cibolo': ['CenterPoint'],
  'cisco': ['AEP Texas'],
  'clarksville city': ['CenterPoint'],
  'cleburne': ['Oncor'],
  'cleveland': ['CenterPoint'],
  'clifton': ['TNMP'],
  'clyde': ['AEP Texas'],
  'coahoma': ['Oncor'],
  'colleyville': ['Oncor'],
  'collinsville': ['Oncor'],
  'colmesneil': ['CenterPoint'],
  'colorado city': ['Oncor'],
  'columbus': ['AEP Texas'],
  'comanche': ['Oncor'],
  'combes': ['AEP Texas'],
  'commerce': ['Oncor'],
  'company': ['AEP Texas'],
  'company will': ['AEP Texas'],
  'comstock': ['AEP Texas'],
  'concepcion': ['AEP Texas'],
  'controlling': ['AEP Texas'],
  'converse': ['CenterPoint'],
  'cooksville': ['CenterPoint'],
  'coppell': ['Oncor', 'TNMP'],
  'copperas cove': ['Oncor'],
  'corinth': ['Oncor'],
  'corpus christi': ['AEP Texas'],
  'corrigan': ['CenterPoint'],
  'cotulla': ['AEP Texas'],
  'covington': ['TNMP'],
  'crawford': ['TNMP'],
  'crockett': ['CenterPoint'],
  'cross cut': ['AEP Texas'],
  'cross plains': ['AEP Texas'],
  'crowell': ['AEP Texas'],
  'crowley': ['Oncor'],
  'crystal city': ['AEP Texas'],
  'dacosta': ['AEP Texas'],
  'daingerfield': ['CenterPoint'],
  'dallas': ['Oncor'],
  'dalworthington gardens': ['Oncor'],
  'dayton': ['CenterPoint'],
  'de soto': ['Oncor'],
  'dean': ['TNMP'],
  'deberry': ['CenterPoint'],
  'dekalb': ['CenterPoint'],
  'del rio': ['AEP Texas'],
  'del valle': ['CenterPoint'],
  'deleon': ['Oncor'],
  'denison': ['Oncor'],
  'deport': ['TNMP'],
  'derby': ['AEP Texas'],
  'detroit': ['TNMP'],
  'devine': ['AEP Texas'],
  'dhanis': ['CenterPoint'],
  'diana': ['CenterPoint'],
  'diboll': ['CenterPoint'],
  'dickens': ['AEP Texas'],
  'dilley': ['AEP Texas'],
  'dodge': ['CenterPoint'],
  'donna': ['AEP Texas'],
  'douglassville': ['CenterPoint'],
  'driscoll': ['CenterPoint', 'AEP Texas'],
  'duncanville': ['Oncor'],
  'eagle lake': ['CenterPoint', 'AEP Texas'],
  'eagle pass': ['AEP Texas'],
  'early': ['Oncor'],
  'east mountain': ['CenterPoint'],
  'eastham': ['CenterPoint'],
  'eastland': ['Oncor'],
  'edcouch': ['AEP Texas'],
  'eden': ['AEP Texas'],
  'edgecliff village': ['Oncor'],
  'edgewood': ['CenterPoint'],
  'edinburg': ['AEP Texas'],
  'edna': ['CenterPoint', 'AEP Texas'],
  'edroy': ['CenterPoint', 'AEP Texas'],
  'effective date': ['AEP Texas'],
  'effectuate the': ['AEP Texas'],
  'el campo': ['CenterPoint', 'AEP Texas'],
  'el cenizo': ['AEP Texas'],
  'el indio': ['AEP Texas'],
  'el maton': ['AEP Texas'],
  'eldorado': ['AEP Texas'],
  'elgin': ['CenterPoint'],
  'eliasville': ['TNMP'],
  'elkhart': ['CenterPoint'],
  'elliot': ['AEP Texas'],
  'ellis - ferguson': ['CenterPoint'],
  'elsa laguna vista': ['AEP Texas'],
  'elton': ['AEP Texas'],
  'elysian fields': ['CenterPoint'],
  'emory': ['TNMP'],
  'encinal': ['AEP Texas'],
  'encino': ['AEP Texas'],
  'ennis': ['Oncor'],
  'eola': ['AEP Texas'],
  'escobares': ['AEP Texas'],
  'eula': ['AEP Texas'],
  'euless': ['Oncor'],
  'evadale': ['CenterPoint'],
  'everman': ['Oncor'],
  'fairview': ['Oncor'],
  'falfurrias': ['AEP Texas'],
  'falls city': ['CenterPoint'],
  'farmers branch': ['Oncor'],
  'farmers valley': ['AEP Texas'],
  'farmersville': ['TNMP'],
  'fate': ['Oncor'],
  'flomot': ['AEP Texas'],
  'floresville': ['CenterPoint'],
  'flower mound': ['Oncor'],
  'forest hill': ['Oncor'],
  'fort chadbourne': ['AEP Texas'],
  'fort davis': ['AEP Texas'],
  'fort stockton': ['TNMP'],
  'fort worth': ['Oncor'],
  'fourth': ['AEP Texas'],
  'freer': ['CenterPoint', 'AEP Texas'],
  'frisco': ['Oncor'],
  'fronton': ['AEP Texas'],
  'frost': ['Oncor'],
  'fruitvale': ['CenterPoint'],
  'fulton': ['AEP Texas'],
  'gainesville': ['Oncor'],
  'ganado': ['CenterPoint', 'AEP Texas'],
  'garden ridge': ['CenterPoint'],
  'garland': ['Oncor'],
  'garwood': ['AEP Texas'],
  'gasoline': ['AEP Texas'],
  'gatesville': ['TNMP'],
  'george west': ['AEP Texas'],
  'giddings': ['CenterPoint'],
  'gillett': ['AEP Texas'],
  'gilmer': ['CenterPoint'],
  'girard': ['AEP Texas'],
  'girvin': ['AEP Texas'],
  'gladewater': ['CenterPoint'],
  'glen': ['TNMP'],
  'glenn': ['AEP Texas'],
  'glenn heights': ['Oncor'],
  'glidden': ['AEP Texas'],
  'goliad': ['CenterPoint', 'AEP Texas'],
  'goodlett': ['AEP Texas'],
  'goodrich': ['CenterPoint'],
  'gordon': ['TNMP'],
  'goree': ['AEP Texas'],
  'grand prairie': ['Oncor'],
  'grand saline': ['CenterPoint'],
  'granger': ['Oncor'],
  'granjeno': ['AEP Texas'],
  'grapeland': ['CenterPoint'],
  'grapevine': ['Oncor'],
  'grayback': ['AEP Texas'],
  'gregory': ['CenterPoint', 'AEP Texas'],
  'gresham': ['CenterPoint'],
  'groveton': ['CenterPoint'],
  'guadalupe': ['AEP Texas'],
  'gustine': ['TNMP'],
  'hallettsville': ['CenterPoint'],
  'hallsville': ['CenterPoint'],
  'haltom city': ['Oncor'],
  'hamilton': ['TNMP'],
  'hamlin': ['AEP Texas'],
  'hargill': ['AEP Texas'],
  'harker heights': ['Oncor'],
  'harleton': ['CenterPoint'],
  'harlingen': ['AEP Texas'],
  'harrold': ['AEP Texas'],
  'haskell': ['AEP Texas'],
  'haslet': ['Oncor'],
  'hatchell': ['AEP Texas'],
  'havana': ['AEP Texas'],
  'hawkins': ['CenterPoint'],
  'hawley': ['AEP Texas'],
  'heath': ['Oncor'],
  'hebbronville': ['CenterPoint', 'AEP Texas'],
  'hefner': ['AEP Texas'],
  'henderson': ['CenterPoint'],
  'henrietta': ['Oncor'],
  'hewitt': ['Oncor'],
  'hico walnut springs': ['TNMP'],
  'hidalgo': ['AEP Texas'],
  'highland park': ['Oncor'],
  'hillje': ['AEP Texas'],
  'hondo': ['CenterPoint'],
  'honey grove': ['Oncor'],
  'hooks': ['CenterPoint'],
  'howe': ['Oncor'],
  'hudson': ['CenterPoint'],
  'hughes springs': ['CenterPoint'],
  'huntsville': ['CenterPoint'],
  'hurst': ['Oncor'],
  'hutto': ['Oncor'],
  'impact': ['AEP Texas'],
  'imperial': ['AEP Texas'],
  'indian lake': ['AEP Texas'],
  'inez': ['CenterPoint', 'AEP Texas'],
  'ingleside': ['CenterPoint', 'AEP Texas'],
  'ingleside on the bay': ['CenterPoint', 'AEP Texas'],
  'iowa park': ['Oncor'],
  'iraan': ['AEP Texas'],
  'irving': ['Oncor'],
  'jacksonville': ['CenterPoint'],
  'january 1 2017': ['AEP Texas'],
  'jasper': ['CenterPoint'],
  'jayton': ['AEP Texas'],
  'jefferson': ['CenterPoint'],
  'jolly': ['Oncor'],
  'jonesville': ['CenterPoint'],
  'josephine': ['Oncor'],
  'jourdanton': ['CenterPoint', 'AEP Texas'],
  'junction': ['AEP Texas'],
  'justin': ['Oncor'],
  'karnack': ['CenterPoint'],
  'karnes city': ['CenterPoint', 'AEP Texas'],
  'kaufman': ['Oncor'],
  'keller': ['Oncor'],
  'kenedy': ['CenterPoint', 'AEP Texas'],
  'kennedale': ['Oncor'],
  'kerens': ['Oncor'],
  'kermit': ['TNMP'],
  'kilgore': ['CenterPoint'],
  'killeen': ['Oncor'],
  'kingsville': ['CenterPoint', 'AEP Texas'],
  'kirbyville': ['CenterPoint'],
  'kirkland': ['AEP Texas'],
  'knickerbocker': ['AEP Texas'],
  'knippa': ['AEP Texas'],
  'knox city': ['AEP Texas'],
  'kopperl': ['TNMP'],
  'krum': ['Oncor'],
  'kyle': ['CenterPoint'],
  'la blanca': ['AEP Texas'],
  'la casita -garciasville': ['AEP Texas'],
  'la feria': ['AEP Texas'],
  'la grange': ['CenterPoint'],
  'la grulla': ['AEP Texas'],
  'la joya': ['AEP Texas'],
  'la marque': ['TNMP'],
  'la pryor': ['AEP Texas'],
  'la villa': ['AEP Texas'],
  'lacoste': ['CenterPoint'],
  'laguna heights': ['AEP Texas'],
  'laird hill': ['CenterPoint'],
  'lake city': ['AEP Texas'],
  'lake worth': ['Oncor'],
  'lakeside': ['Oncor', 'AEP Texas'],
  'lamar': ['AEP Texas'],
  'lamesa': ['Oncor'],
  'lamkin': ['TNMP'],
  'lancaster': ['Oncor'],
  'laredo': ['CenterPoint', 'AEP Texas'],
  'latexo': ['CenterPoint'],
  'laureles': ['AEP Texas'],
  'lawn': ['AEP Texas'],
  'league city': ['TNMP'],
  'leakey': ['AEP Texas'],
  'leary': ['CenterPoint'],
  'leesville': ['AEP Texas'],
  'leggett': ['CenterPoint'],
  'leming': ['AEP Texas'],
  'lessburg': ['CenterPoint'],
  'lewisville': ['Oncor'],
  'liberty': ['CenterPoint'],
  'lindale': ['Oncor'],
  'linden': ['CenterPoint'],
  'little elm': ['Oncor'],
  'little river academy': ['Oncor'],
  'livingston': ['CenterPoint'],
  'lockett': ['AEP Texas'],
  'lolita': ['CenterPoint'],
  'lone oak': ['TNMP'],
  'lone star': ['CenterPoint'],
  'long mott': ['AEP Texas'],
  'longview': ['CenterPoint'],
  'longworth': ['AEP Texas'],
  'los ebanos': ['AEP Texas'],
  'los fresnos': ['AEP Texas'],
  'los indios': ['AEP Texas'],
  'louise': ['CenterPoint', 'AEP Texas'],
  'lovelady': ['CenterPoint'],
  'loving': ['TNMP'],
  'lowry crossing': ['TNMP'],
  'lozano': ['AEP Texas'],
  'lubbock': ['LP&L'],
  'lueders': ['AEP Texas'],
  'lufkin': ['CenterPoint'],
  'luling': ['AEP Texas'],
  'lumberton': ['CenterPoint'],
  'lyford': ['AEP Texas'],
  'lytle': ['AEP Texas'],
  'madero': ['AEP Texas'],
  'malakoff': ['Oncor'],
  'mansfield': ['Oncor'],
  'marathon': ['AEP Texas'],
  'marfa': ['AEP Texas'],
  'margaret': ['AEP Texas'],
  'marion': ['CenterPoint'],
  'markham': ['AEP Texas'],
  'marshall': ['CenterPoint'],
  'matador': ['AEP Texas'],
  'matagorda': ['AEP Texas'],
  'mathis': ['CenterPoint', 'AEP Texas'],
  'matthews': ['AEP Texas'],
  'maud': ['CenterPoint'],
  'mauriceville': ['CenterPoint'],
  'may': ['AEP Texas'],
  'may 29 2020': ['AEP Texas'],
  'mcadoo': ['AEP Texas'],
  'mcallen': ['AEP Texas'],
  'mccamey': ['AEP Texas'],
  'mccaulley': ['AEP Texas'],
  'mckinney': ['Oncor'],
  'mcleod': ['CenterPoint'],
  'mcqueeney': ['CenterPoint'],
  'medicine mound': ['AEP Texas'],
  'megargel': ['TNMP'],
  'melvin': ['AEP Texas'],
  'menard': ['AEP Texas'],
  'mercedes': ['AEP Texas'],
  'mereta': ['AEP Texas'],
  'meridian': ['TNMP'],
  'merkel': ['AEP Texas'],
  'mertzon': ['AEP Texas'],
  'mesquite': ['Oncor'],
  'midfield': ['AEP Texas'],
  'midland': ['Oncor'],
  'midlothian': ['Oncor'],
  'miles': ['AEP Texas'],
  'millers cove': ['CenterPoint'],
  'millett': ['AEP Texas'],
  'mineola': ['CenterPoint'],
  'mingus': ['TNMP'],
  'mirando city': ['CenterPoint', 'AEP Texas'],
  'mission': ['AEP Texas'],
  'montague': ['TNMP'],
  'monte alto': ['AEP Texas'],
  'moore': ['AEP Texas'],
  'moran': ['AEP Texas'],
  'morgan': ['TNMP'],
  'mt pleasant': ['CenterPoint'],
  'mt vernon': ['CenterPoint'],
  'munday': ['AEP Texas'],
  'murchison': ['Oncor'],
  'murphy': ['Oncor'],
  'nacogdoches': ['CenterPoint'],
  'nada': ['AEP Texas'],
  'naples': ['CenterPoint'],
  'nash': ['CenterPoint'],
  'natalia': ['AEP Texas'],
  'neches': ['CenterPoint'],
  'nederland': ['CenterPoint'],
  'new boston': ['CenterPoint'],
  'new braunfels': ['CenterPoint'],
  'new chapel hill': ['Oncor'],
  'new london': ['CenterPoint'],
  'new willard': ['CenterPoint'],
  'newcastle': ['TNMP'],
  'niederwald': ['CenterPoint'],
  'nimrod': ['AEP Texas'],
  'nixon': ['AEP Texas'],
  'nocona': ['TNMP'],
  'noodle': ['AEP Texas'],
  'nordheim': ['CenterPoint', 'AEP Texas'],
  'normandy': ['AEP Texas'],
  'normanna': ['AEP Texas'],
  'north cleveland': ['CenterPoint'],
  'north richland hills': ['Oncor'],
  'northlake': ['Oncor'],
  'norton': ['AEP Texas'],
  'nottingham woods': ['CenterPoint'],
  'oak leaf': ['Oncor'],
  'oak point': ['Oncor'],
  'oakville': ['AEP Texas'],
  'obrien': ['AEP Texas'],
  'odell': ['AEP Texas'],
  'odem': ['CenterPoint', 'AEP Texas'],
  'odessa': ['Oncor'],
  'odonnell': ['Oncor'],
  'oilton': ['CenterPoint', 'AEP Texas'],
  'oklaunion': ['AEP Texas'],
  'old glory': ['AEP Texas'],
  'old ocean': ['TNMP'],
  'olmito': ['AEP Texas'],
  'olney': ['TNMP'],
  'omaha': ['CenterPoint'],
  'orange': ['CenterPoint'],
  'orange grove': ['CenterPoint', 'AEP Texas'],
  'ore city': ['CenterPoint'],
  'original': ['AEP Texas'],
  'ovalo': ['AEP Texas'],
  'overton': ['CenterPoint'],
  'ovilla': ['Oncor'],
  'ozona': ['AEP Texas'],
  'paducah': ['AEP Texas'],
  'paint rock': ['AEP Texas'],
  'palacios': ['CenterPoint', 'AEP Texas'],
  'palestine': ['Oncor'],
  'palm valley': ['AEP Texas'],
  'palmhurst': ['AEP Texas'],
  'palmview': ['AEP Texas'],
  'pantego': ['Oncor'],
  'paris': ['Oncor'],
  'pattonville': ['TNMP'],
  'pawnee': ['AEP Texas'],
  'peacock': ['AEP Texas'],
  'pearland': ['TNMP'],
  'pearsall': ['AEP Texas'],
  'pecos': ['TNMP'],
  'penitas': ['AEP Texas'],
  'pernitas point': ['AEP Texas'],
  'petrolia': ['TNMP'],
  'petronila': ['AEP Texas'],
  'pettus': ['CenterPoint', 'AEP Texas'],
  'pharr': ['AEP Texas'],
  'pilot point': ['TNMP'],
  'pine forest': ['CenterPoint'],
  'pinehurst': ['CenterPoint'],
  'pioneer': ['AEP Texas'],
  'pittsburg': ['CenterPoint'],
  'placedo': ['CenterPoint', 'AEP Texas'],
  'plano': ['Oncor'],
  'pleasanton': ['CenterPoint', 'AEP Texas'],
  'point': ['TNMP'],
  'point comfort': ['CenterPoint', 'AEP Texas'],
  'policies for such access': ['AEP Texas'],
  'port aransas': ['AEP Texas'],
  'port isabel': ['AEP Texas'],
  'port lavaca': ['CenterPoint', 'AEP Texas'],
  'port mansfield': ['AEP Texas'],
  'portland': ['CenterPoint', 'AEP Texas'],
  'poteet': ['CenterPoint', 'AEP Texas'],
  'poth': ['CenterPoint'],
  'potosi': ['AEP Texas'],
  'pottsboro': ['Oncor'],
  'premont': ['CenterPoint', 'AEP Texas'],
  'presidio': ['AEP Texas'],
  'price': ['CenterPoint'],
  'primera': ['AEP Texas'],
  'princeton': ['TNMP'],
  'pritchett': ['CenterPoint'],
  'progreso': ['AEP Texas'],
  'progreso lakes': ['AEP Texas'],
  'prosper': ['Oncor'],
  'putnam': ['AEP Texas'],
  'quanah': ['AEP Texas'],
  'queen city': ['CenterPoint'],
  'quemado': ['AEP Texas'],
  'quitaque': ['AEP Texas'],
  'rabb': ['AEP Texas'],
  'ramireno': ['AEP Texas'],
  'ramirez': ['AEP Texas'],
  'rancho viejo': ['AEP Texas'],
  'randolph': ['TNMP'],
  'ranger': ['Oncor'],
  'rankin': ['AEP Texas'],
  'rayburn hills': ['CenterPoint'],
  'rayland': ['AEP Texas'],
  'raymondville': ['AEP Texas'],
  'realitos': ['AEP Texas'],
  'red lick': ['CenterPoint'],
  'redford': ['AEP Texas'],
  'redwater': ['CenterPoint'],
  'refugio': ['CenterPoint', 'AEP Texas'],
  'revision': ['AEP Texas'],
  'rhome': ['Oncor'],
  'ricardo': ['AEP Texas'],
  'richardson': ['Oncor'],
  'richland': ['Oncor'],
  'richland hills': ['Oncor'],
  'ringgold': ['TNMP'],
  'rio bravo': ['AEP Texas'],
  'rio grande city': ['AEP Texas'],
  'rio hondo': ['AEP Texas'],
  'rio vista': ['TNMP'],
  'rios tynan': ['AEP Texas'],
  'rising star': ['AEP Texas'],
  'river oaks': ['Oncor'],
  'rivera': ['AEP Texas'],
  'riverside': ['CenterPoint'],
  'roanoke': ['Oncor'],
  'roaring springs': ['AEP Texas'],
  'robert lee': ['AEP Texas'],
  'robinson': ['Oncor'],
  'roby': ['AEP Texas'],
  'rochelle': ['AEP Texas'],
  'rochester': ['AEP Texas'],
  'rockport': ['AEP Texas'],
  'rocksprings': ['AEP Texas'],
  'rockwall': ['Oncor'],
  'roma -los saenz': ['AEP Texas'],
  'rose': ['TNMP'],
  'rose city': ['CenterPoint'],
  'rose hill acres': ['CenterPoint'],
  'rosser': ['Oncor'],
  'rotan': ['AEP Texas'],
  'rowena': ['AEP Texas'],
  'rowlett': ['Oncor'],
  'royston': ['AEP Texas'],
  'rule': ['AEP Texas'],
  'runge': ['CenterPoint', 'AEP Texas'],
  'rusk': ['CenterPoint'],
  'sabinal': ['AEP Texas'],
  'sachse': ['Oncor'],
  'sagerton': ['AEP Texas'],
  'saginaw': ['Oncor'],
  'saint jo': ['TNMP'],
  'san angelo': ['AEP Texas'],
  'san augustine': ['CenterPoint'],
  'san benito': ['AEP Texas'],
  'san carlos': ['AEP Texas'],
  'san diego': ['CenterPoint', 'AEP Texas'],
  'san juan': ['AEP Texas'],
  'san marcos': ['CenterPoint'],
  'san patricio': ['AEP Texas'],
  'san perlita': ['AEP Texas'],
  'san ygnacio': ['AEP Texas'],
  'sanderson': ['TNMP'],
  'sandia': ['AEP Texas'],
  'sansom park': ['Oncor'],
  'santa anna': ['AEP Texas'],
  'santa maria': ['AEP Texas'],
  'santa monica': ['AEP Texas'],
  'santa rosa': ['AEP Texas'],
  'santo': ['TNMP'],
  'saragosa': ['AEP Texas'],
  'saratoga': ['CenterPoint'],
  'schertz': ['CenterPoint'],
  'schulenberg': ['CenterPoint'],
  'scottsville': ['CenterPoint'],
  'scranton': ['AEP Texas'],
  'seadrift': ['CenterPoint', 'AEP Texas'],
  'seagoville': ['Oncor'],
  'sebastian': ['AEP Texas'],
  'seco mines': ['AEP Texas'],
  'section 22': ['AEP Texas'],
  'section title': ['AEP Texas'],
  'sedwick': ['AEP Texas'],
  'seguin': ['CenterPoint'],
  'sejita': ['AEP Texas'],
  'selma': ['CenterPoint'],
  'september 1 2009': ['TNMP'],
  'seven sisters': ['AEP Texas'],
  'shafter': ['AEP Texas'],
  'sheffield': ['AEP Texas'],
  'shepherd': ['CenterPoint'],
  'sherman': ['Oncor'],
  'sherwood': ['AEP Texas'],
  'silsbee': ['CenterPoint'],
  'sinton': ['CenterPoint', 'AEP Texas'],
  'skidmore': ['CenterPoint', 'AEP Texas'],
  'slocum': ['CenterPoint'],
  'smiley': ['AEP Texas'],
  'smithville': ['CenterPoint'],
  'snyder': ['Oncor'],
  'sonora': ['AEP Texas'],
  'sour lake': ['CenterPoint'],
  'south padre island': ['AEP Texas'],
  'southlake': ['Oncor'],
  'splendora': ['CenterPoint'],
  'spofford': ['AEP Texas'],
  'springtown': ['Oncor'],
  'spur': ['AEP Texas'],
  'stamford': ['AEP Texas'],
  'stephenville': ['Oncor'],
  'sterling city': ['AEP Texas'],
  'stowell': ['CenterPoint'],
  'strawn': ['TNMP'],
  'sullivan city': ['AEP Texas'],
  'sulphur springs': ['Oncor'],
  'sunnyvale': ['Oncor'],
  'swan': ['CenterPoint'],
  'sweeny': ['TNMP'],
  'sweetwater': ['Oncor'],
  'swenson': ['AEP Texas'],
  'sylvan': ['TNMP'],
  'sylvester': ['AEP Texas'],
  'taft': ['CenterPoint', 'AEP Texas'],
  'talco': ['CenterPoint', 'TNMP'],
  'talpa': ['AEP Texas'],
  'tankersley': ['AEP Texas'],
  'tatum': ['CenterPoint'],
  'temple': ['Oncor'],
  'tenaha': ['CenterPoint'],
  'tennessee colony': ['CenterPoint'],
  'terrell': ['Oncor'],
  'texarkana': ['CenterPoint'],
  'texas city': ['TNMP'],
  'thalia': ['AEP Texas'],
  'the colony': ['Oncor'],
  'the provisions of this': ['AEP Texas'],
  'three rivers': ['AEP Texas'],
  'throckmorton': ['AEP Texas'],
  'thurber': ['TNMP'],
  'timpson': ['CenterPoint'],
  'tiogo': ['TNMP'],
  'tivoli': ['AEP Texas'],
  'tolar': ['TNMP'],
  'tom bean': ['TNMP'],
  'toyah': ['TNMP'],
  'toyahvale': ['AEP Texas'],
  'trent': ['AEP Texas'],
  'trenton': ['TNMP'],
  'trinity': ['CenterPoint'],
  'trophy club': ['Oncor'],
  'troup': ['CenterPoint'],
  'truscott': ['AEP Texas'],
  'tuleta': ['CenterPoint', 'AEP Texas'],
  'tulsita': ['AEP Texas'],
  'turkey': ['AEP Texas'],
  'turnertown': ['CenterPoint'],
  'tuscola': ['AEP Texas'],
  'tye': ['AEP Texas'],
  'tyler': ['Oncor', 'CenterPoint'],
  'uncertain': ['CenterPoint'],
  'union grove': ['CenterPoint'],
  'universal city': ['CenterPoint'],
  'university park': ['Oncor'],
  'uvalde': ['AEP Texas'],
  'valentine': ['AEP Texas'],
  'valera': ['AEP Texas'],
  'valley mills': ['TNMP'],
  'van': ['CenterPoint'],
  'vanderbilt': ['CenterPoint'],
  'venus': ['Oncor'],
  'veribest': ['AEP Texas'],
  'vernon': ['AEP Texas'],
  'victoria': ['CenterPoint', 'AEP Texas'],
  'victoria gardens': ['CenterPoint'],
  'vidor': ['CenterPoint'],
  'view': ['AEP Texas'],
  'violet': ['AEP Texas'],
  'waco': ['Oncor'],
  'wadsworth': ['AEP Texas'],
  'wake village': ['CenterPoint'],
  'wall': ['AEP Texas'],
  'warren city': ['CenterPoint'],
  'waskom': ['CenterPoint'],
  'watauga': ['Oncor'],
  'water valley': ['AEP Texas'],
  'waxahachie': ['Oncor'],
  'weesatche': ['AEP Texas'],
  'weimar': ['CenterPoint'],
  'weinert': ['AEP Texas'],
  'weldon': ['CenterPoint'],
  'weslaco': ['AEP Texas'],
  'west columbia': ['TNMP'],
  'west orange': ['CenterPoint'],
  'westhoff': ['AEP Texas'],
  'westminister': ['TNMP'],
  'westover hills': ['Oncor'],
  'white oak': ['CenterPoint'],
  'white settlement': ['Oncor'],
  'whitehouse': ['CenterPoint'],
  'whiteland': ['AEP Texas'],
  'whitewright': ['TNMP'],
  'whitney': ['TNMP'],
  'wichita falls': ['Oncor'],
  'wickett': ['TNMP'],
  'willow park': ['Oncor'],
  'wills point': ['CenterPoint'],
  'wilmeth': ['AEP Texas'],
  'winfield': ['CenterPoint'],
  'wingate': ['AEP Texas'],
  'wink': ['TNMP'],
  'winnie': ['CenterPoint'],
  'winnsboro': ['CenterPoint'],
  'winter haven': ['AEP Texas'],
  'winters': ['AEP Texas'],
  'woodsboro': ['AEP Texas'],
  'woodson': ['AEP Texas'],
  'woodway': ['Oncor'],
  'wylie': ['Oncor'],
  'yorktown': ['AEP Texas'],
  'zapata': ['AEP Texas'],
} as const;

export const TEXAS_TDU_CITY_KEYS = Object.keys(TEXAS_TDU_BY_CITY);

export type TexasTduName = (typeof TEXAS_TDU_BY_CITY)[keyof typeof TEXAS_TDU_BY_CITY][number];
