steps:
  # Build the Backend Node.js server (server.js)
  - name: 'gcr.io/cloud-builders/docker'
    args: 
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/nodal-point-network:$COMMIT_SHA'
    - '-f'
    - 'Dockerfile'
    - '.'
  
  # Push the Backend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nodal-point-network:$COMMIT_SHA']
  
  # Deploy Backend to Cloud Run (nodal-point-network)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'nodal-point-network'
    - '--image'
    - 'gcr.io/$PROJECT_ID/nodal-point-network:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8080'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--cpu-throttling'
    - '--min-instances'
    - '0'
    - '--max-instances'
    - '10'
    - '--concurrency'
    - '80'
    - '--set-env-vars'
    - 'NODE_ENV=production,API_BASE_URL=https://nodal-point-network-792458658491.us-central1.run.app,PUBLIC_BASE_URL=https://nodalpoint.io,NEXT_PUBLIC_SUPABASE_URL=https://gfitvnkaevozbcyostez.supabase.co,NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmaXR2bmthZXZvemJjeW9zdGV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkyNjI3OTUsImV4cCI6MjA4NDgzODc5NX0.hDnsWEVwZW9vQJTDB_YILCVs1-dJKjj7OkGcrbazEg0,SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdmaXR2bmthZXZvemJjeW9zdGV6Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2OTI2Mjc5NSwiZXhwIjoyMDg0ODM4Nzk1fQ.qIWfuParcwPGNphHhqixAk9Pd1dPXTGra57qVRGEYGY'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/nodal-point-network:$COMMIT_SHA'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
