steps:
  # Build the container image using the Next.js Dockerfile in crm-platform
  - name: 'gcr.io/cloud-builders/docker'
    args: 
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/power-choosers-crm:$COMMIT_SHA'
    - '-f'
    - 'crm-platform/Dockerfile'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}'
    - '--build-arg'
    - 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}'
    - '--build-arg'
    - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}'
    - '.'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/power-choosers-crm:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'power-choosers-crm'
    - '--image'
    - 'gcr.io/$PROJECT_ID/power-choosers-crm:$COMMIT_SHA'
    - '--region'
    - 'us-south1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '3000'
    - '--memory'
    - '512Mi'
    - '--cpu'
    - '1'
    - '--cpu-throttling'
    - '--min-instances'
    - '0'
    - '--max-instances'
    - '10'
    - '--concurrency'
    - '40'
    - '--set-env-vars'
    - 'NODE_ENV=production,LOG_LEVEL=warn,VERBOSE_LOGS=false,NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID},NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID},NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET},NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN},NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY},PERPLEXITY_API_KEY=${_PERPLEXITY_API_KEY},CRON_SECRET=${_CRON_SECRET},GOOGLE_MAPS_API=${_GOOGLE_MAPS_API},CI_AUTO_PROCESS=${_CI_AUTO_PROCESS},APOLLO_API_KEY=${_APOLLO_API_KEY},TWILIO_INTELLIGENCE_SERVICE_SID=${_TWILIO_INTELLIGENCE_SERVICE_SID},API_BASE_URL=${_API_BASE_URL},PUBLIC_BASE_URL=${_PUBLIC_BASE_URL},GEMINI_API_KEY=${_GEMINI_API_KEY},FIREBASE_CLIENT_EMAIL=${_FIREBASE_CLIENT_EMAIL},FIREBASE_PRIVATE_KEY=${_FIREBASE_PRIVATE_KEY},FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID},TWILIO_ACCOUNT_SID=${_TWILIO_ACCOUNT_SID},TWILIO_AUTH_TOKEN=${_TWILIO_AUTH_TOKEN},TWILIO_API_KEY_SID=${_TWILIO_API_KEY_SID},TWILIO_API_KEY_SECRET=${_TWILIO_API_KEY_SECRET},TWILIO_TWIML_APP_SID=${_TWILIO_TWIML_APP_SID},SUPABASE_SERVICE_ROLE_KEY=${_SUPABASE_SERVICE_ROLE_KEY},TWILIO_PHONE_NUMBER=${_TWILIO_PHONE_NUMBER},GOOGLE_SERVICE_ACCOUNT_KEY=${_GOOGLE_SERVICE_ACCOUNT_KEY},GMAIL_SENDER_EMAIL=${_GMAIL_SENDER_EMAIL},GMAIL_SENDER_NAME=${_GMAIL_SENDER_NAME},FREE_GEMINI_KEY=${_FREE_GEMINI_KEY},OPEN_ROUTER_API_KEY=${_OPEN_ROUTER_API_KEY},GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID},GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET}'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/power-choosers-crm:$COMMIT_SHA'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  # machineType removed - using Cloud Build default (e2-medium) to avoid enum parsing issues
  # Default machine type is cost-effective and sufficient for most builds

