steps:
  # Build the container image using the Next.js Dockerfile in crm-platform
  - name: 'gcr.io/cloud-builders/docker'
    args: 
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/power-choosers-crm:$COMMIT_SHA'
    - '-f'
    - 'crm-platform/Dockerfile'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}'
    - '--build-arg'
    - 'NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}'
    - '--build-arg'
    - 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}'
    - '--build-arg'
    - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}'
    - '.'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/power-choosers-crm:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'power-choosers-crm'
    - '--image'
    - 'gcr.io/$PROJECT_ID/power-choosers-crm:$COMMIT_SHA'
    - '--region'
    - 'us-south1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '3000'
    - '--memory'
    - '512Mi'
    - '--cpu'
    - '1'
    - '--cpu-throttling'
    - '--min-instances'
    - '0'
    - '--max-instances'
    - '10'
    - '--concurrency'
    - '40'
    - '--set-env-vars'
    - 'NODE_ENV=production'
    - '--set-env-vars'
    - 'LOG_LEVEL=warn'
    - '--set-env-vars'
    - 'VERBOSE_LOGS=false'
    - '--set-env-vars'
    - 'SENDGRID_WEBHOOK_SECRET=${_SENDGRID_WEBHOOK_SECRET}'
    - '--set-env-vars'
    - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}'
    - '--set-env-vars'
    - 'NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}'
    - '--set-env-vars'
    - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}'
    - '--set-env-vars'
    - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}'
    - '--set-env-vars'
    - 'NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}'
    - '--set-env-vars'
    - 'PERPLEXITY_API_KEY=${_PERPLEXITY_API_KEY}'
    - '--set-env-vars'
    - 'CRON_SECRET=${_CRON_SECRET}'
    - '--set-env-vars'
    - 'SENDGRID_FROM_NAME=${_SENDGRID_FROM_NAME}'
    - '--set-env-vars'
    - 'SENDGRID_FROM_EMAIL=${_SENDGRID_FROM_EMAIL}'
    - '--set-env-vars'
    - 'SENDGRID_API_KEY=${_SENDGRID_API_KEY}'
    - '--set-env-vars'
    - 'GOOGLE_MAPS_API=${_GOOGLE_MAPS_API}'
    - '--set-env-vars'
    - 'CI_AUTO_PROCESS=${_CI_AUTO_PROCESS}'
    - '--set-env-vars'
    - 'CORESIGNAL_API_KEY=${_CORESIGNAL_API_KEY}'
    - '--set-env-vars'
    - 'APOLLO_API_KEY=${_APOLLO_API_KEY}'
    - '--set-env-vars'
    - 'TWILIO_INTELLIGENCE_SERVICE_SID=${_TWILIO_INTELLIGENCE_SERVICE_SID}'
    - '--set-env-vars'
    - 'API_BASE_URL=${_API_BASE_URL}'
    - '--set-env-vars'
    - 'PUBLIC_BASE_URL=${_PUBLIC_BASE_URL}'
    - '--set-env-vars'
    - 'GEMINI_API_KEY=${_GEMINI_API_KEY}'
    - '--set-env-vars'
    - 'FIREBASE_CLIENT_EMAIL=${_FIREBASE_CLIENT_EMAIL}'
    - '--set-env-vars'
    - 'FIREBASE_PRIVATE_KEY=${_FIREBASE_PRIVATE_KEY}'
    - '--set-env-vars'
    - 'FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}'
    - '--set-env-vars'
    - 'TWILIO_ACCOUNT_SID=${_TWILIO_ACCOUNT_SID}'
    - '--set-env-vars'
    - 'TWILIO_AUTH_TOKEN=${_TWILIO_AUTH_TOKEN}'
    - '--set-env-vars'
    - 'TWILIO_API_KEY_SID=${_TWILIO_API_KEY_SID}'
    - '--set-env-vars'
    - 'TWILIO_API_KEY_SECRET=${_TWILIO_API_KEY_SECRET}'
    - '--set-env-vars'
    - 'TWILIO_TWIML_APP_SID=${_TWILIO_TWIML_APP_SID}'
    - '--set-env-vars'
    - 'SUPABASE_SERVICE_ROLE_KEY=${_SUPABASE_SERVICE_ROLE_KEY}'
    - '--set-env-vars'
    - 'TWILIO_PHONE_NUMBER=${_TWILIO_PHONE_NUMBER}'
    - '--set-env-vars'
    - 'GOOGLE_SERVICE_ACCOUNT_KEY=${_GOOGLE_SERVICE_ACCOUNT_KEY}'
    - '--set-env-vars'
    - 'GMAIL_SENDER_EMAIL=${_GMAIL_SENDER_EMAIL}'
    - '--set-env-vars'
    - 'GMAIL_SENDER_NAME=${_GMAIL_SENDER_NAME}'
    - '--set-env-vars'
    - 'FREE_GEMINI_KEY=${_FREE_GEMINI_KEY}'
    - '--set-env-vars'
    - 'OPEN_ROUTER_API_KEY=${_OPEN_ROUTER_API_KEY}'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/power-choosers-crm:$COMMIT_SHA'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  # machineType removed - using Cloud Build default (e2-medium) to avoid enum parsing issues
  # Default machine type is cost-effective and sufficient for most builds

