// Maps high-level industry vectors to specific Supabase industry values
export const INDUSTRY_VECTORS: Record<string, string[]> = {
  'Manufacturing': [
    'Manufacturing',
    '3D Printing Materials',
    'Agricultural Plastics Manufacturing',
    'Battery Manufacturing',
    'Building Materials',
    'Building Materials Manufacturing',
    'Building Products',
    'Building Systems',
    'Chemical Manufacturing',
    'Electric Lighting Equipment Manufacturing',
    'Electrical & Electronic Manufacturing',
    'Electronics Assembly',
    'Electronics Manufacturing',
    'Equipment Manufacturing',
    'Furniture Manufacturing',
    'Hydraulic Components Manufacturing',
    'Industrial Assembly',
    'Industrial Equipment',
    'Industrial Machinery & Equipment',
    'Industrial Products',
    'Industrial Pump Manufacturing',
    'Manufacturing Services',
    'Manufacturing Support',
    'Manufacturing, Food & Beverage',
    'Medical Device Manufacturing',
    'Motor Vehicle Manufacturing',
    'Optical Equipment Manufacturing',
    'Optical Manufacturing',
    'Pipe Manufacturing',
    'Plastics Manufacturing',
    'Precision Components',
    'Precision Manufacturing',
    'Seismic Equipment Manufacturing',
    'Specialty Chemical Manufacturing',
    'Specialty Steel Manufacturing',
    'Steel Manufacturing',
    'Supplement Manufacturing',
    'Technology Manufacturing',
    'automotive',
    'aviation & aerospace',
    'building materials',
    'business supplies & equipment',
    'chemicals',
    'computer hardware',
    'defense & space',
    'electrical/electronic manufacturing',
    'furniture',
    'industrial automation',
    'machinery',
    'mechanical or industrial engineering',
    'medical devices',
    'mining & metals',
    'nanotechnology',
    'packaging & containers',
    'paper & forest products',
    'pharmaceuticals',
    'plastics',
    'printing',
    'semiconductors',
    'textiles',
    'glass, ceramics & concrete'
  ],
  'Healthcare': [
    'Healthcare',
    'Health Care and Social Assistance',
    'Assisted Living And Memory Care',
    'Hospitals, Healthcare & Clinics',
    'Nursing Homes and Residential Care Facilities',
    'biotechnology',
    'health, wellness & fitness',
    'hospital & health care',
    'individual & family services',
    'medical practice',
    'mental health care',
    'veterinary'
  ],
  'Real Estate': [
    'Real Estate',
    'Construction',
    'Construction Services',
    'Engineering & Construction',
    'architecture & planning',
    'civil engineering',
    'construction',
    'facilities services',
    'commercial real estate',
    'residential real estate'
  ],
  'Retail': [
    'Retail',
    'Retail Distribution',
    'Retailer',
    'Distribution',
    'Distribution Services',
    'Sporting Goods Distribution',
    'Wholesale Building Materials',
    'Wholesaler',
    'apparel & fashion',
    'consumer goods',
    'consumer services',
    'cosmetics',
    'import & export',
    'luxury goods & jewelry',
    'sporting goods',
    'supermarkets',
    'wholesale',
    'wine & spirits'
  ],
  'Education': [
    'Education',
    'School district office',
    'education management',
    'e-learning',
    'higher education',
    'primary/secondary education',
    'research'
  ],
  'Technology': [
    'Technology',
    'IT Services',
    'Information',
    'Technology Services',
    'Travel Technology',
    'computer & network security',
    'computer networking',
    'computer software',
    'information services',
    'information technology & services',
    'internet',
    'telecommunications',
    'Telecommunications Services'
  ],
  'Energy': [
    'Energy',
    'Oil & Gas',
    'Oil & Gas Production',
    'Oil, Gas & Mining',
    'oil & energy',
    'renewables & environment',
    'utilities'
  ],
  'Food & Beverage': [
    'Food & Beverage',
    'Accommodation and Food Services',
    'Agriculture Processing',
    'Food & Beverage Manufacturing',
    'Food Distribution',
    'Food Processing',
    'Ice Manufacturing',
    'Manufacturing, Food & Beverage',
    'dairy',
    'farming',
    'fishery',
    'food & beverages',
    'food production',
    'hospitality',
    'ranching',
    'restaurants'
  ],
  'Services': [
    'Services',
    'Administrative and Support Services',
    'Business Services',
    'Cross-border Logistics',
    'Finance and Insurance',
    'Financial Services/Housing Finance',
    'Hospitality',
    'Non-profit Organization Management',
    'Professional, Scientific, and Technical Services',
    'Public Administration',
    'Transportation Services',
    'Transportation and Warehousing',
    'Warehousing & 3PL Services',
    'Waste Management and Remediation Services',
    'accounting',
    'airlines/aviation',
    'banking',
    'capital markets',
    'design',
    'entertainment',
    'environmental services',
    'events services',
    'executive office',
    'financial services',
    'government administration',
    'human resources',
    'insurance',
    'international trade & development',
    'investment banking',
    'investment management',
    'law enforcement',
    'legal services',
    'logistics & supply chain',
    'management consulting',
    'maritime',
    'marketing & advertising',
    'media production',
    'nonprofit organization management',
    'package/freight delivery',
    'performing arts',
    'philanthropy',
    'photography',
    'public relations and communications',
    'public safety',
    'publishing',
    'recreational facilities & services',
    'security and investigations',
    'staffing & recruiting',
    'translation and localization',
    'transportation/trucking/railroad',
    'venture capital & private equity',
    'warehousing',
    'writing & editing'
  ]
};

// Helper to get all industry strings for a given set of vectors
export function getIndustryFilters(selectedVectors: string[]): string[] {
  return selectedVectors.flatMap(vector => INDUSTRY_VECTORS[vector] || [vector]);
}
