-- Enable vector extension just in case
create extension if not exists vector;

create table if not exists public.market_telemetry (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  timestamp text,
  prices jsonb,
  grid jsonb,
  metadata jsonb,
  embedding vector(768)
);

-- Add HNSW index for vector search
create index if not exists market_telemetry_embedding_idx 
on public.market_telemetry 
using hnsw (embedding vector_cosine_ops);

-- Enable RLS
alter table public.market_telemetry enable row level security;

-- Create policy to allow read access for all users
create policy "Enable read access for all users"
on public.market_telemetry
for select
using (true);

-- Create policy to allow insert/update/delete for service role only (default behavior if no policy)
-- But explicit policies are good practice.
-- Actually, let's allow authenticated users to read.
